### ISSUE TITLE
deployment_url can no longer be passed to candlepin

### ISSUE THREAD

**Issue by mdellweg** [Katello/puppet-katello_devel#123]
https://github.com/Katello/puppet-katello_devel/blob/5ee68ce508526f62797df950e5b2db47ca408d8f/manifests/init.pp#L114

This line breaks forklift devel. I think the problem started with this:
https://github.com/Katello/puppet-candlepin/pull/82

**Comment by ekohl** [comment]
Apologies, I always forget this module. See the related PR for the fix.
